# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d329d2778f06f03d71e19c757e7566c917a5cb31ca62435ba1b408cdb08b69f2e7c4520a73f744553454a67418bf520aa96d61849e726143aa8c9ed537b45cb

test:
  secret_key_base: 58ec5dd335e97692273c8e62ce6f392e78bffee3a776e1afbaaa344588360c184d220e2f16252f049afbbdc68a7351c6571da66c33c1a54f393bebd3d22994b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
